config/routes.rb
Musicianfinder::Application.routes.draw do
  root :to => 'users#index'

  resources :password_resets
  resources :user_sessions
  resources :users do
    resources :references
    resources :invitations, shallow: true
  end
  patch '/invitations/:id/read' => "invitations#read", as: "toggle_read_invitation"

  get 'tags/:tag', to: 'users#index', as: :tag

  get 'join' => 'users#new'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:first_name, :last_name, :city, :bio, :looking_for]
  scope :all_except, ->(user) { where.not(id: user) }

  has_many :target_references, class_name: "Reference", foreign_key: :target_id
  has_many :source_references, class_name: "Reference", foreign_key: :source_id

  has_many :invitations
  has_many :invitations_received, class_name: "Invitation", foreign_key: :recipient_id
  has_many :invitations_sent, class_name: "Invitation", foreign_key: :user_id

  has_attached_file :avatar, :styles => {
                    :medium => "300x300>",
                    :thumb => "100x100>",
                    :mini => "30x30" }, :default_url => "/images/:attachment/missing_:style.png"

  before_validation { self.postal_code = postal_code.upcase }

  before_save { self.smart_add_url }
  before_save { self.email = email.downcase }

  validates_length_of :password, minimum: 6, on: :create
  validates_confirmation_of :password

  validates_length_of :first_name, :maximum => 35
  validates_length_of :last_name, :maximum => 35

  validates_presence_of :postal_code

  validates_format_of :first_name, :with => /[a-z]/
  validates_format_of :last_name, :with => /[a-z]/
  validates_format_of :postal_code, :with => /\A[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}[ -]?\d{1}[A-Z]{1}\d{1}\z/

  validates_presence_of :email
  validates_uniqueness_of :email
  after_validation :geocode, :if => :postal_code_changed?

  authenticates_with_sorcery!
  geocoded_by :postal_code

  acts_as_taggable
  acts_as_taggable_on :genres, :instruments

  def full_name
    if first_name.present? && last_name.present?
      full_name = (first_name.capitalize + " " + last_name.capitalize)
    end
  end

  def smart_add_url
    if self.personal_url.present?
      self.personal_url = "http://#{self.personal_url}" unless self.personal_url[/\Ahttps?:\/\//]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]
  before_filter :set_user, only: [:show, :edit, :update, :destroy]
  #before_filter :debug

  def index
      #select option doesn't appear unless current_user
    return @users = current_user.nearbys if params[:sort] == "near"

    return @users = User.tagged_with(params[:tag]) if params[:tag]

    if params[:query] && PgSearch.multisearch(params[:query]).length >= 1
      search = PgSearch.multisearch(params[:query])
      @users = search.map(&:searchable)
    else
      @users = current_user.present? ? User.all_except(current_user) : User.all
    end

      respond_to do |format|
      format.html
      format.js {}
      end
  end

  def show
    @recipient = User.find(params[:id])
      if current_user
        @reference = @user.target_references.build
        @invitation = Invitation.new
        @invitation.recipient_id = @recipient.id
      end
  end

  def new
    @user = User.new()
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save

        auto_login(@user)
        #Send a welcome email
        UserMailer.welcome_email(@user).deliver

        format.html { redirect_to(:users, notice: 'Welcome to Homebass.') }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user)
                         .permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :first_name,
                                 :last_name,
                                 :city,
                                 :postal_code,
                                 :bio,
                                 :instrument_list,
                                 :genre_list,
                                 :latitude,
                                 :longitude,
                                 :looking_for,
                                 :personal_url,
                                 :avatar)
  end

  def debug
    puts params.inspect
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_reference.html.erb
<% if current_user %>

  <h3>Change the Reference you left for <%= @user.first_name %></h3>

  <%= form_for([@user, @reference]) do |f| %>
    <div id="reference-form-errors" >
       <%= render 'shared/reference_form_errors' %>
    </div>

    <br/>
    <%= f.text_area :comment %>

    <%= f.radio_button :feedback_value, 1 %>
    <%= f.label :feedback_value, "Positive" %>

    <%= f.radio_button :feedback_value, 0 %>
    <%= f.label :feedback_value, "Neutral" %>

    <%= f.radio_button :feedback_value, -1 %>
    <%= f.label :feedback_value, "Negative" %>

    <%= f.check_box :jammed %>
    <%= f.label :jammed, "We've jammed together" %>

    <%= f.check_box :performed %>
    <%= f.label :performed, "We've performed together" %>

    <%= f.check_box :recorded %>
    <%= f.label :recorded, "We've recorded together" %>

    <%= f.submit "Update Reference",:class => "button radius tiny" %>

  <% end %>
<% else %>
  <p>Please <%= link_to 'log in', new_session_path %> to leave a reference.</p>
<% end %>
<hr>
<%= link_to "Back to My References", user_references_path %>

app/views/users/_feedback_rating.html.erb
<ul>
  <li><b>Total: <%= @user.target_references.sum(:feedback_value) %></li><b>
  <b><li>Quality: <%= number_to_percentage((100*
  @user.target_references.where(feedback_value: 1).count /
   [(@user.target_references.where(feedback_value: 1).count +
   @user.target_references.where(feedback_value: -1).count),1].max.to_f), precision: 1) %></li><b>
</ul>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="row">
    <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">

    <div class="row">
      <div class="required">
        <div class="small-6 columns">
          <%= f.label :first_name, "First Name" %>
          <%= f.text_field :first_name %>
        </div>
        <div class="small-6 columns">
          <%= f.label :last_name, "Last Name" %>
          <%= f.text_field :last_name %>
        </div>
      </div>
    </div>

      <div class="required">

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.label :postal_code, "Postal Code (used to find nearby musicians)"  %>
        <%= f.text_field :postal_code %>
      </div>

        <%= f.label "Genres (separated by commas)" %>
        <%= f.text_field :genre_list %>

        <%= f.label "Instruments (separated by commas)" %>
        <%= f.text_field :instrument_list %>
    </div>

    <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">
      <%= f.label "City" %>
      <%= f.text_field :city %>

      <%= f.label "Biography" %>
      <%= f.text_area :bio %>

      <%= f.label "What are you looking for?" %>
      <%= f.text_area :looking_for %>

      <%= f.label "Link to Recordings, Band Site etc."  %>
      <%= f.text_field :personal_url %>

      <%= f.label "Choose a Photo" %>
      <%= f.file_field :avatar %>

    </div>
  </div>

<div class="row">
  <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">
    <%= f.submit "Save", :class => "radius button small" %>
  <% end %>
  </div>
</div>

app/views/users/_new_message.html.erb
<h4>Contact <%= @user.first_name.capitalize %></h4>

  <%= form_for([@user, @invitation], remote: true ) do |f| %>
    <div id="message-form-errors" >
      <%= render 'shared/message_form_errors' %>
    </div>

    <%= f.hidden_field :recipient_id %>


    <%= f.text_area :content %>

    <%= f.submit "Send Message", :class => "button radius small" %>
  <% end %>

app/views/users/_new_reference.html.erb
<% if current_user %>

<h4>Leave a Reference for <%= @user.first_name.capitalize %></h4>

  <%= form_for([@user, @reference], remote: true ) do |f| %>
    <div id="reference-form-errors" >
      <%= render 'shared/reference_form_errors' %>
    </div>

    <%= f.text_area :comment %>
    <div>
      <%= f.radio_button :feedback_value, 1 %>
      <%= f.label :feedback_value, "Positive" %>

      <%= f.radio_button :feedback_value, 0 %>
      <%= f.label :feedback_value, "Neutral" %>

      <%= f.radio_button :feedback_value, -1 %>
      <%= f.label :feedback_value, "Negative" %>
    </div>
    <div>
      <%= f.check_box :jammed %>
      <%= f.label :jammed, "We've jammed together" %>
    </div>
    <div>
      <%= f.check_box :performed %>
      <%= f.label :performed, "We've performed together" %>
    </div>
    <div>
      <%= f.check_box :recorded %>
      <%= f.label :recorded, "We've recorded together" %>
    </div>

    <%= f.submit "Leave Reference", class: "button radius small" %>
  <% end %>
<% else %>
  <p>Please <%= link_to 'log in', new_session_path %> to leave a reference.</p>
<% end %>

app/views/users/_references.html.erb
<% @user.target_references.each do |reference| %>
  <li>
    <% unless reference.new_record? %>
      <div class="<%= reference.feedback_textifier %>">Feedback: <%= reference.feedback_textifier %>
      </div>
      Comment: <%= reference.comment %><br>
      Jammed Together? <%= reference.check("jammed") %><br>
      Performed?  <%= reference.check("performed")  %><br>
      Recorded?  <%= reference.check("recorded") %><br>
        <% if reference.source != nil %>
          <em>Left By: <%=link_to reference.source.full_name, "/users/#{reference.source.id}" %></em><br>
          Date: <%= reference.created_at.to_formatted_s(:long) %>
        <% end %>
    </li>
  <% end %>
<% end %>

app/views/users/_reply.html.erb
<div class="row">
   <div class="small-10 small-centered columns">
    <%= form_for([@user, @reply], remote: true ) do |f| %>
      <div id="message-form-errors">
        <%= render 'shared/message_form_errors' %>
      </div>
    </div>


    <%= f.hidden_field :recipient_id, value: "#{@invitation.user_id}" %>

      <%= f.label "Reply" %>
      <%= f.text_area :content %>
      <%= f.submit "Send", :class => "button radius small"  %>
  <% end %>
</div>

app/views/users/_sort.html.erb
  <select id="sort">
    <option value="all">Everyone</option>
    <option value="near">Near Me</option>
  </select>
  <br>

app/views/users/_users.html.erb
 <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
      <% @users.each do |user| %>
        <li>
          <div id="musician-home-block">
            <div id="musician-name-img">
              <div class="user-name">
                <%= link_to "#{user.full_name}", user_path(user.id) %>
                <span title="Score based on other users feedback">
                  (<%= user.target_references.sum(:feedback_value) %>)
                </span>
              </div>
              <div id="musician-img">
                <%=link_to image_tag(user.avatar.url(:thumb)), user_path(user.id) %>
              </div>
              <hr />
            </div>
            <span class="user-attr">Genres:</span>
              <%= raw user.genre_list.map { |t| link_to t, tag_path(t) }.join(', ') %><br>
            <span class="user-attr">Instruments:</span>
              <%= raw user.instrument_list.map { |t| link_to t, tag_path(t) }.join(', ') %><br>
            <span class="user-attr">City:</span> <%= user.city %>
              <% if current_user %>-
                <%= user.distance_to(current_user, :km).round(1) %> KM from you
              <% end %><br>
            <span class="user-attr">Biography:</span>
              <%= truncate(user.bio, length: 120) %><br>
            <span class="user-attr">Looking for:</span>
              <%= truncate(user.looking_for, length: 80) %>
          </li>
        <% end %>
    </ul>
  </div>

app/views/users/edit.html.erb
<div class="row">
  <h1>Update your profile</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
  <%= render 'sort' if current_user %>
</div>

<div class="row">
  <div class="small-10 small-centered medium-8 large-8 columns" id="container">
    <div class="title">Canada's #1 Source for Non-Flakey Musicians!</div>
    <div class="tag-line">
      Find musicians who play the instruments and genres you're interested in.<br/>
      Share your good and not-so-good experiences with other musicians.<br/>
      Start contacting people near you today!<br/>
        <% unless current_user %>
          <br/><%= link_to("Join Today", join_path, :class => "button radius") %>
        <% end %><br/>
    </div>
  </div>
</div>

<div class="row">
<br>
  <div id="users"><%= render 'users' %></div>

</div>

app/views/users/index.js.erb
$("#users").html('<%= escape_javascript(render :partial => "users") %>')

app/views/users/new.html.erb
<div class="row">
  <div class="small-10 medium-8 large-6 columns">
	<h1>Register</h1>
    <h4>We will never sell your information. Ever!</h4>
  </div>
</div>
<hr/>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="small-9 columns">
      <div id="musician-show-bio">
        <div id="musician-name-img">
          <div class="user-name">
        </div>
          <h2><%= @user.full_name %></h2>
            <div id="musician-show-img">
              <%= image_tag @user.avatar.url(:medium) %>
            </div>
            <hr />
        </div>

        <span class="show-attr">City:</span> <%= @user.city %>
         <% if current_user != @user %>
          - <%= @user.distance_to(current_user, :km).round(1) %> KM from you
        <% end %><br>
        <span class="show-attr">Genres:</span>
          <%= @user.genre_list %><br>
        <span class="show-attr">Instruments:</span>
          <%= @user.instrument_list %><br>

        <span class="show-attr">Biography:</span>
          <%= @user.bio %><br><br>
        <span class="show-attr">Looking for:</span>
          <%= @user.looking_for %><br><br>
          <a href=<%="#{@user.personal_url}"%>>My Website</a>
    </div>
  </div>

  <div class="small-2 end medium-3 columns">
    <h3>Feedback Rating</h3>
    <div id="feedback-rating">
      <%= render "feedback_rating" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">
  <ul>
    <li id="new-message">
      <%= render "new_message" %>
    </li>
   </ul>
  </div>

  <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">
    <ul>
      <li id="new-reference">
        <%= render "new_reference" %>
      </li>
    </ul>
  </div>
</div>


<div class="row" id="ref">
  <div class="small-10 small-centered medium-8 large-uncentered large-6 columns">
  <% if @user.target_references.count >= 1 %>
    <h4>References left for <%= @user.first_name.capitalize %></h4>
  <% else %>
    <h4>Be the first to leave a reference for <%= @user.first_name.capitalize %>!</h4>
  <% end %>
</div>
<hr/>
    <ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-3" id="references">
    <%= render "references" %>
  </ul>
</div>