config/routes.rb
Musicianfinder::Application.routes.draw do
  root :to => 'users#index'

  resources :password_resets
  resources :user_sessions
  resources :users do
    resources :references
    resources :invitations, shallow: true
  end
  patch '/invitations/:id/read' => "invitations#read", as: "toggle_read_invitation"

  get 'tags/:tag', to: 'users#index', as: :tag

  get 'join' => 'users#new'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
  validates_presence_of :content, :user_id, :recipient_id
  default_scope -> { order('created_at DESC') }

  validate :check_self_send

  def check_self_send
    errors.add(:base, "You can't message yourself") if user_id == recipient_id
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :load_user, except: [:read, :show]

  def index
    redirect_to root_url unless current_user == @user
    @invitations = Invitation.all
  end

  def show
	  @invitation = Invitation.find(params[:id])
	  @user = User.find(@invitation.recipient_id)
    redirect_to root_url unless current_user == @user
    @reply = Invitation.new
  end

  def new
	  @invitation = Invitation.new
  end

  def read
	  @user = current_user
	  @invitation = Invitation.find(params[:id])

    if current_user.id == @invitation.recipient_id
	   @invitation.toggle!(:recipient_read)
    else
     @invitation.toggle!(:sender_read)
    end

	  if @invitation.save
	    redirect_to user_invitations_path(@user)
	  else
	    redirect_to user_path(@user)
	  end
  end

  def create
	  @invitation = @user.invitations.build(invitation_params)
	  @invitation.user_id = current_user.id
    respond_to do |format|
    	if @invitation.save
  	    format.html {redirect_to user_path(@user), notice: 'Message Sent'}
        format.js{}
  	  else
  	    format.html { redirect_to user_path(@user), notice: 'Message can not be blank' }
        format.js{}
  	  end
    end
  end

  private
  def invitation_params
    params.require(:invitation).permit(:content, :recipient_id, :user_id)
  end

  def correct_user

  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/create.js.erb
<% if @invitation.errors.present? %>
  $("#message-form-errors").html("<%= escape_javascript(render(:partial => '/shared/message_form_errors')) %>");
<% else %>
  $("#message-form-errors").html("<%= escape_javascript(render(:partial => '/shared/message_form_errors')) %>");
  alert("Message Sent");
<% end %>

app/views/invitations/index.html.erb
<div class="row">
  <div class="small-10 small-centered columns">
        <h2>Inbox</h2>
    <table>
      <thead>
        <tr>
          <th width="100">From</th>
          <th width="500">Message</th>
          <th width="150">Sent</th>
          <th width="130">Status</th>
        </tr>
      </thead>
          <% @user.invitations_received.each do |invite| %>
        <tbody>
          <tr class="<%= 'unread_mail' unless invite.recipient_read %>">
            <td><%= link_to "#{invite.user.full_name}", user_path(invite.user_id) %></td>
            <td><%= link_to invite.content, invitation_path(invite)  %></td>
            <td><%= invite.created_at.to_formatted_s(:long) %></td>
            <td>
            <% if invite.recipient_read %>
              <%= link_to "Mark as unread", toggle_read_invitation_path(invite), method: :patch %>
            <% else %>
              <%= link_to "Mark as read", toggle_read_invitation_path(invite), method: :patch %>
            <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>

        <h2>Sent</h2>
    <table>
      <thead>
        <tr>
          <th width="100">To</th>
          <th width="500">Message</th>
          <th width="150">Sent</th>
          <th width="130">Status</th>
        </tr>
      </thead>
        <% @user.invitations_sent.each do |invite| %>
      <tbody>
        <tr class="<%= 'unread_mail' unless invite.sender_read %>">
          <td><%= link_to "#{invite.recipient.full_name}", user_path(invite.recipient_id) %></td>
          <td><%= simple_format invite.content %></td>
          <td><%= invite.created_at.to_formatted_s(:long) %></td>
           <td>
            <% if invite.sender_read %>
              <%= link_to "Mark as unread", toggle_read_invitation_path(invite), method: :patch  %>
            <% else %>
              <%= link_to "Mark as read", toggle_read_invitation_path(invite), method: :patch %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
    </table>
  </div>
</div>

app/views/invitations/show.html.erb
<div class="row">
  <div class="small-10 small-centered columns">
    <h3><%= link_to "Back to Inbox", user_invitations_path(@user) %></h3>
    <table>
      <thead>
        <tr>
          <th width="100">From</th>
          <th width="500">Message</th>
   	      <th width="150">Sent</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to "#{@invitation.user.full_name}", "/users/#{@invitation.user_id}" %></td>
          <td><%= simple_format @invitation.content %></td>
          <td><%= @invitation.created_at.to_formatted_s(:long) %></td>
        </tr>
      </tbody>
    </table>
    <%= render "users/reply" %>
  </div>
</div>