config/routes.rb
Musicianfinder::Application.routes.draw do
  root :to => 'users#index'

  resources :password_resets
  resources :user_sessions
  resources :users do
    resources :references
    resources :invitations, shallow: true
  end
  patch '/invitations/:id/read' => "invitations#read", as: "toggle_read_invitation"

  get 'tags/:tag', to: 'users#index', as: :tag

  get 'join' => 'users#new'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
  	@user = User.new
  end

  def create
  	if @user = login(params[:email], params[:password], params[:remember])
  		redirect_back_or_to :users, notice: 'Login Successful'
  	else
  		flash.now[:alert] = 'Login Failed'
  		render action: 'new'
  	end
  end

  def destroy
  	logout
  	redirect_to(:users, notice: 'Logged Out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<div class="row" id="pwd_reset">
  <div class="small-10 small-centered medium-8 large-6 columns">
<h1>Forgot Password?</h1>
    <%= form_tag password_resets_path, :method => :post do %>
      <%= label_tag :email %>
      <%= text_field_tag :email %>
       <%= submit_tag "Reset my password", class: "radius small button" %>
      <% end %>
    </div>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="row" id="login">
  <div class="small-10 small-centered medium-8 large-6 columns">
    <%= form_tag user_sessions_path, :method => :post do %>
  <h1>Login</h1>
      <%= label_tag :email %>
      <%= text_field_tag :email %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag "Login", :class => "radius button" %>
    <% end %>
  </div>
</div>

<%= render 'forgot_password_form' %>