config/routes.rb
Musicianfinder::Application.routes.draw do
  root :to => 'users#index'

  resources :password_resets
  resources :user_sessions
  resources :users do
    resources :references
    resources :invitations, shallow: true
  end
  patch '/invitations/:id/read' => "invitations#read", as: "toggle_read_invitation"

  get 'tags/:tag', to: 'users#index', as: :tag

  get 'join' => 'users#new'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="../favicon.png">

    <title><%= content_for?(:title) ? yield(:title) : "HomeBass" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans|Raleway" rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
    <body>
    <!-- Navigation Bar from Foundation Template -->
      <div class="fixed">
        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <li class="name">
              <h1><a href="/">HomeBass</a></h1>
            </li>
            <li class="toggle-topbar menu-icon">
              <a href="#"><span>menu</span></a>
            </li>
          </ul>
          <section class="top-bar-section">
            <ul class="right">
              <li>
                <%= form_tag users_path, :method => :get do %>
                  <%= text_field_tag :query, params[:query], placeholder: "Search" %>
                <% end %>
              </li>
            <% if current_user %>
              <li>
                <%= link_to "My Messages(#{current_user.invitations_received.where(recipient_read: false).count})", user_invitations_path(current_user.id) %>
              </li>
              <li class="mini-photo hide-for-small">
              <%= link_to image_tag(current_user.avatar.url(:mini)), user_path(current_user.id) %>
              </li>
              <li class="show-for-small">
                <%= link_to "My Profile", user_path(current_user.id) %>
              </li>
              <li class="show-for-small">
                <%= link_to "My References", user_references_path(current_user.id) %>
              </li>
              <li li class="show-for-small">
                <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
              </li>
              <li li class="show-for-small">
                <%= link_to "Logout", :logout, method: :post %>
              </li>
              <li class="has-dropdown hide-for-small">
                <a href="#">
                  <%= link_to "#{current_user.first_name.capitalize}", user_path(current_user.id) %>
                </a>
                <ul class="dropdown">
                  <li>
                    <%= link_to "My References", user_references_path(current_user.id) %>
                  </li>
                  <li>
                    <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
                  </li>
                  <li>
                    <%= link_to "Logout", :logout, method: :post %>
                  </li>
              <% else %>
                  <ul class="right">
                  <li>
                    <%= link_to "Register", join_path %>
                  </li>
                  <li>
                    <%= link_to "Login", :login %>
                  </li>
                </ul>
              <% end %>
                </ul>
              </li>
            </ul>
          </section>
        </nav>
      </div>

      <div>
        <p id="notice"><%= flash[:notice] %></p>
        <p id="alert"><%= flash[:alert] %></p>
      </div>

      <%= yield %>
      <%= javascript_include_tag "application" %>
  </body>
</html>